apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropopss
  name: giropopss
spec:
  containers:
  - image: nginx
    name: giropopss
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}